src/features/deposit/components/Table.jsx

fixed bug no - 34 for module deposit where now user can use copy and paste in the input field .

fixed copy and paste in the utr and id and user submit utr in deposit module

---

src/redux/api.jsx

- Temporarily Increased the size of pagination to `1000` if url is `getall-merchant`.

Temporarily Increased the size of pagination

---

src/components/reports/PayinComponent.jsx
src/components/reports/PayoutComponent.jsx
src/components/reports/index.jsx
src/features/bankAccounts/components/Table.jsx
src/features/dashboard/components/MerchantCodeSelectBox.jsx
src/features/deposit/All/index.jsx
src/features/deposit/completed/index.jsx
src/features/deposit/components/Table.jsx
src/features/deposit/dropped/index.jsx
src/features/deposit/inProgress/index.jsx
src/features/merchants/components/AddMerchant.jsx
src/features/merchants/components/DeleteModal.jsx
src/features/merchants/components/Table.jsx
src/features/merchants/components/UpdateMerchant.jsx
src/features/settlement/components/Columns.jsx
src/features/vendorsettlement/components/Columns.jsx
src/features/withdraw/components/Columns.jsx
src/features/withdraw/index.jsx
src/utils/utils.js

1. vendor filter in banks page
2. merchant details shouldn't be there in vendor account i.e. in deposit table
3. in payout page when we click new payout merchant code field is able to search the merchant
4. edit delete functionality in Merchant Module
5. In withdrawal module should have tick and cross button, instead of approve or reject
6. Add a copy button against API key and merchant code in merchant module
7. Payout callback field should be there while adding merchants from the merchant module
8. In Merchant login the dashboard module and in new payment link modal in Deposit Module should be locked with the merchant’s name and no input will be accepted

New Development

---

src/features/withdraw/index.jsx

now the payout input filed will not prevent for any account number.

the account number now will be valid

---

src/features/settlement/index.jsx
src/features/vendorsettlement/index.jsx

- Changed Settlement Wallet Selector into Input.
- Modified Approval Modal if method is not bank
- Added `refrence_id` as `empty space` if for update settlement API if method is not bank.

Changed Wallet Selector to Input And updated API payload.

---

src/features/settlement/index.jsx
src/features/vendorsettlement/index.jsx

- Fixed the `BANK` method check spell issue fixed.

BANK METHOD comparison check fixed

---

src/features/bankAccounts/components/Table.jsx

On reset set filter values to initial state

On reset set filter values to initial state

---

src/features/withdraw/components/Columns.jsx

the prevent number entry removed from the withdrawal module ColumnSearch

Fixed withdraw module ColumnSearch

---

src/utils/utils.js

- Changed the `FAILED` status to `DROPPED` in both payIn and payout Reports statuses.

changed Failed status to Dropped in Reports

---

src/features/merchants/components/Table.jsx
src/features/merchants/components/UpdateMerchant.jsx

Password verification on edit/delete merchant records

Password verification on edit/delete in Merchant Module

---

src/features/deposit/components/Table.jsx

add reset buttons for DUPLICATE AND DISPUTE  .

Benjamin reset transaction task

---

src/features/dashboard/components/MerchantCodeSelectBox.jsx
src/features/vendorBoard/components/VendorCodeSelectBox.jsx

bug fixed for dropdown close after selecting the vendor code and merchant code

bug fixed for dropdown close 

---

src/features/bankAccounts/All/index.jsx
src/features/bankAccounts/components/AddBankAccount.jsx
src/features/bankAccounts/components/Table.jsx
src/features/withdraw/components/Columns.jsx
src/features/withdraw/components/Table.jsx
src/features/withdraw/index.jsx

1. Add selection for the usage of bank while adding bank
2. Display used of bank in table
3. Add selection of Payout bank while approving withdrawal
4. Display selected bank name in withdraw table

Differentiate payin/payout banks

---

src/components/Roles/components/Table.jsx
src/features/bankAccounts/components/AddBankAccount.jsx
src/features/bankAccounts/components/Table.jsx

1. Verifying the password at the time of deleting bank account in Bank Account Module 
2. Verifying the password while enabling and disabling the user in User Module

Password verification in Bank Account and User Module

---

src/features/withdraw/components/Columns.jsx
src/features/withdraw/components/Table.jsx
src/features/withdraw/index.jsx

Display added vendor in table
remove check box if got vendor in data or status is success/rejected

withdrawal check box bug

---

src/components/ConfirmOverRideModal/index.jsx

A new warning text added for the login page .

text changed for the warning line on login page

---

src/components/reports/index.jsx
src/features/dashboard/components/MerchantCodeSelectBox.jsx
src/features/deposit/components/Table.jsx
src/features/vendorsettlement/components/Columns.jsx
src/features/withdraw/components/Columns.jsx
src/features/withdraw/index.jsx

- Added Clear buttons in:
- Reports Merchant Selector.
- Merchant Select Box in dashboard.
- Added search options in:
- Merchant Selector in New Payment Link.
- Restricted Alphabets and Enabled Numeric in:
- Bank Account Field of Settlement.
- Reference Id field of Settlement.

Minor bug fixes and improvements

---

src/features/deposit/components/Table.jsx
src/features/vendorBoard/components/VendorCodeSelectBox.jsx
src/features/vendors/components/Table.jsx
src/utils/utils.js

bug solved for pagination , and added reload to reset for duplicate and disput.

Benjo reload bug

---

src/features/bankAccounts/components/Table.jsx
src/features/withdraw/components/Columns.jsx

1. Show UTR details in completed page in Withdrawal Module 
2. Show balance for today with the count of successful payin transaction in Bank Account Module

Bug fixed in Withdrawal and Bank Account Module

---

src/features/bankAccounts/components/Table.jsx

Added edit bank details on bank details for editing detail of bank , ifsc m account and upi.

refactor :Created a bank account edit Model for bank account edit

---

src/features/dashboard/components/MerchantCodeSelectBox.jsx

Dashboard data reflecting in merchant_Admin login

Bug fixed in Dashboard Module

---

src/features/deposit/components/Table.jsx

image col removed for roles VENDOR_OPERATIONS ,MERCHANT_ADMIN , MERCHANT_OPERATIONS ,MERCHANT

Refactor: Image col

---

src/features/dashboard/components/MerchantCodeSelectBox.jsx
src/features/merchants/components/UpdateMerchant.jsx
src/features/settlement/index.jsx
src/features/withdraw/index.jsx

1. In merchant_module edit merchant unable to input floating number, User able to change payin/payout range condition, auto refresh not working.
2. In Withdrawal_module range should be as per merchant payout range, user only withdrawal within range.

Bugs fixes on [24/10/2024]

---

src/features/bankAccounts/components/Table.jsx
src/features/deposit/components/Table.jsx
src/features/settlement/index.jsx

1. In deposits module ---> In In progress, completed and dropped submodules, when user search and filter anything getting results and then hitting on reset button ,getting all transactions
2. In bank_module when user click on the reset button, user get previous day transactions data. 
3. In settlement module UTR Field should be alphanumeric unrestricted while approving.

Bugs 4/11/24

---

src/features/addData/components/CheckUTR.jsx
src/features/addData/components/ResetEntry.jsx
src/features/addData/components/Table.jsx

1. check utr functionality in add data
2. reset option in add data

New Features

---

src/components/WebSockets/WebSockets.jsx
src/features/addData/All/index.jsx

- Added checks before refreshing the data in table.

Fixed Socket Refresh in Add Data Module

---

src/features/merchants/components/Table.jsx
src/features/withdraw/index.jsx

1. Remove some columns and removed columns will only visible to ADMIN
2. Remove condition from create Withdrawal

UI Changes
